var config = {
    texts: [
        "🎂🎂🎂🎂🎂",
        "Best wishes for SZY",
        "2020.12.30",
        "六十天前很高兴认识你",
        "今天衷心祝福你",
        "愿你贪吃不胖",
        "愿你永远精致",
        "愿你永葆青春",
        "愿你有所追求有所热爱",
        "愿你奔赴理想乘风破浪",
        "愿你每天都有好运气",
        "愿这岁月悠长",
        "即使不见亦能不散",
        "若这一切太难",
        "只愿你一生简单一生平安",
        "最后祝你期末门门高分哈哈哈",
        "芝麻生日快乐！",
        "🎂♥🎂",
        "-------FROM LSH",
        "祝芝麻生日快乐",
    ],
    imgs: {
        "祝芝麻生日快乐": "./imgs/xiaokeai.png",
    },
    desc: {
        turn_on: "BEGIN",
        play: "MUSIC",
        bannar_coming: "COLOR",
        balloons_flying: "SOMETHING MISSED?",
        cake_fadein: "CAKE?",
        light_candle: "CANDLE?",
        wish_message: "HAPPY BIRTHDAY",
        story: "A MESSAGE FOR YOU",
    }
};
