var config = {
    texts: [
        "🎂🎂🎂🎂🎂",
        "Best wishes to SZY",
        "2020.12.30",
        "除了祝福之外,还有一些牢骚",
        "😄😄😄",
        "不知你是否相信缘分",
        "六十天前",
        "我刚好睡过",
        "你刚好没走",
        "走完一程远足",
        "我们刚好认识",
        "I want to say that  I like you",
        "But it was not asking for a relationship",
        "Just express my personal feelings",
        "世界这么大,人生这么短",
        "能够遇到一位喜欢的朋友",
        "已然是难得",
        "Be a good friend is already enough",
        "希望未来的你,幸福快乐",
        "好啦,牢骚完了,别介意",
        "😄😄😄",
        "今天是你生日",
        "衷心祝福你",
        "愿你贪吃不胖",
        "愿你美梦不空",
        "愿你纵情豁达",
        "愿你深情不负",
        "愿你永远精致",
        "愿你永葆青春",
        "愿你有所追求有所热爱",
        "愿你奔赴理想乘风破浪",
        "愿你每天都会有好运气",
        "愿你余生",
        "做你愿做的事",
        "爱你愿爱的人",
        "愿这岁月悠长",
        "我们即使不见亦能不散",
        "若这一切太多太难",
        "只愿你的十九岁",
        "简单平安快乐",
        "Be fearless",
        "Be yourself",
        "And if you need",
        "I'll always be there",
        "生日快乐！",
        "Happy Birthday!",
        "Bon Anniversaire!",
        "🎂♥🎂",
        "-------FROM LSH",
        "祝芝麻生日快乐",
    ],
    imgs: {
        "祝芝麻生日快乐": "./imgs/xiaokeai.png",
    },
    desc: {
        turn_on: "BEGIN",
        play: "MUSIC",
        bannar_coming: "COLOR",
        balloons_flying: "SOMETHING MISSED?",
        cake_fadein: "CAKE?",
        light_candle: "CANDLE?",
        wish_message: "HAPPY BIRTHDAY",
        story: "A MESSAGE FOR YOU",
    }
};
