var config = {
    texts: [
        "🎂🎂🎂🎂🎂",
        "Best wishes to YOU",
        "2020.12.30",
        "除了祝福之外,还有一些牢骚",
        "(●'◡'●)",
        "不知你是否相信缘分",
        "六十天前",
        "我刚好睡过",
        "你刚好没走",
        "走完一程远足",
        "我们刚好认识",
        "I want to say that I like you as your friend",
        "But it was not asking for a relationship",
        "Just express my personal feelings",
        "世界这么大,人生这么短",
        "能够遇到一位喜欢的朋友",
        "已然是难得",
        "初见惊艳，愿久处常欢喜",
        "希望未来的你,幸福快乐",
        "好啦,牢骚完了,别介意",
        "(●'◡'●)",
        "今天是你生日",
        "衷心祝福你",
        "愿你贪吃不胖",
        "愿你美梦不空",
        "愿你纵情豁达",
        "愿你深情不负",
        "愿你永远精致",
        "愿你永葆青春",
        "愿你有所追求有所热爱",
        "愿你奔赴理想乘风破浪",
        "愿你每天都会有好运气",
        "愿你余生",
        "做你愿做的事",
        "爱你愿爱的人",
        "愿这岁月悠长",
        "我们即使不见亦能不散",
        "若这一切太多太难",
        "只愿你的十九岁",
        "简单平安快乐",
        "Be fearless",
        "Be yourself",
        "And if you need",
        "I'll always be there",
        "生日快乐！",
        "Happy Birthday!",
        "Bon Anniversaire!",
        "🎂🎂🎂",
        "2020/12/30-FROM LSH",
        "祝芝麻生日快乐",
    ],
    imgs: {
        "🎂🎂🎂🎂🎂": "./imgs/1.png",
        "Best wishes to YOU": "./imgs/2.png",
        "走完一程远足": "./imgs/3.png",
        "我们刚好认识": "./imgs/4.png",
        "希望未来的你,幸福快乐": "./imgs/5.png",
        "今天是你生日": "./imgs/6.png",
        "衷心祝福你": "./imgs/7.png",
        "愿你贪吃不胖": "./imgs/8.png",
        "愿你美梦不空": "./imgs/9.png",
        "愿你纵情豁达": "./imgs/10.png",
        "愿你深情不负": "./imgs/11.png",
        "愿你永远精致": "./imgs/12.png",
        "愿你永葆青春": "./imgs/13.png",
        "愿你有所追求有所热爱": "./imgs/xiaokeai.png",
        "愿你奔赴理想乘风破浪": "./imgs/15.png",
        "愿你每天都会有好运气": "./imgs/17.png",
        "简单平安快乐": "./imgs/16.png",
        "I'll always be there": "./imgs/18.png",
        "祝芝麻生日快乐": "./imgs/19.png",
    },
    desc: {
        turn_on: "BEGIN",
        play: "MUSIC",
        bannar_coming: "BANNAR",
        balloons_flying: "BALLOON",
        cake_fadein: "CAKE",
        light_candle: "CANDLE",
        wish_message: "HAPPY BIRTHDAY",
        story: "A MESSAGE FOR YOU",
    }
};
